// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wsvm_cd_cpp
List wsvm_cd_cpp(NumericMatrix x, IntegerVector y_bin, NumericVector w_obs, double C, int max_iter, double tol);
RcppExport SEXP _SWORD_wsvm_cd_cpp(SEXP xSEXP, SEXP y_binSEXP, SEXP w_obsSEXP, SEXP CSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y_bin(y_binSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_obs(w_obsSEXP);
    Rcpp::traits::input_parameter< double >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(wsvm_cd_cpp(x, y_bin, w_obs, C, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SWORD_wsvm_cd_cpp", (DL_FUNC) &_SWORD_wsvm_cd_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_SWORD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
