# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Weighted linear C-SVM via coordinate descent (bias augmentation)
#'
#' @param x        Numeric matrix (n x p) of scaled features.
#' @param y_bin    Integer vector of class labels in \{-1, +1\}.
#' @param w_obs    Numeric vector of per-observation weights (positive).
#' @param C        SVM cost parameter (default 1.0).
#' @param max_iter Maximum number of full cyclic passes (default 5000).
#' @param tol      Convergence threshold: stop when max|delta_alpha| < tol (default 1e-3).
#'
#' @return A named list with elements \code{w} (primal weights, length p) and
#'   \code{b} (scalar bias); decision = \code{w^T x_scaled + b}.
#' @export
wsvm_cd_cpp <- function(x, y_bin, w_obs, C = 1.0, max_iter = 5000L, tol = 1e-3) {
    .Call(`_SWORD_wsvm_cd_cpp`, x, y_bin, w_obs, C, max_iter, tol)
}

